# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
