# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, verbose_name='Login email address')),
                ('password', models.CharField(max_length=256, verbose_name='Login password')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, verbose_name='Registration email address')),
                ('password', models.CharField(max_length=256, verbose_name='Registration password')),
                ('password_repeat', models.CharField(max_length=256, verbose_name='Registration password repeat')),
            ],
        ),
    ]
