# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Login email address'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Registration email address'),
        ),
    ]
