# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20170720_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weather date')),
                ('min_temp', models.IntegerField(verbose_name='Weather min temp')),
                ('max_temp', models.IntegerField(verbose_name='Weather rain')),
            ],
        ),
    ]
