# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Registration email address')),
                ('password', models.CharField(max_length=256, verbose_name='Registration password')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weather date')),
                ('min_temp', models.IntegerField(verbose_name='Weather min temp')),
                ('max_temp', models.IntegerField(verbose_name='Weather max temp')),
                ('wind', models.IntegerField(verbose_name='Weather wind')),
                ('rain', models.IntegerField(verbose_name='Weather rain')),
            ],
        ),
        migrations.DeleteModel(
            name='LoginForm',
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
