# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20170720_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
